name: UI-tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Корректная установка Playwright и системных зависимостей
      - name: Install Playwright browsers and deps
        run: sudo npx playwright install --with-deps

      - name: Run Playwright tests with pytest and generate Allure result
        run: |
          xvfb-run pytest -m regression --alluredir=./allure-results --numprocesses 2

      # ИСПРАВЛЕНО: Скачиваем историю именно в папку allure-history
      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: allure-history

      # Генерируем отчет (он объединит allure-results и историю из allure-history)
      - name: Allure Report action from marketplace
        uses: mgrybyk-org/allure-report-branch-js-action@v1
        if: always()
        with:
          report_dir: allure-results
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      # Публикуем сгенерированный отчет на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
