name: UI-tests

#Где запускаем тесты
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    #Запуск тестов на ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      #Устанавливаем питон
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      #Устанавливаем зависимости
      - name: Install dependencies  #Устанавливаем зависимости
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps
      #Запускаем автотесты
      - name: Run Playwright tests with pytest and generate Allure result
        run: |
          pytest -m regression --alluredir=./allure-results --numprocesses 2 --headless
      #Получает Allure истории
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      #Скачиваем Allure
      - name: Allure Report action from marketplace
        uses: mgrybyk-org/allure-report-branch-js-action@v1
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      #Публикуем всё на гитХаб паджест
      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh_pages
          PUBLISH_DIR: allure-history


