name: UI-tests

#Где запускаем тесты
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  run-tests:
    #Запуск тестов на ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      #Устанавливаем питон
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      #Устанавливаем зависимости
      - name: Install dependencies  #Устанавливаем зависимости
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps
      #Запускаем автотесты
      - name: Run Playwright tests with pytest and generate Allure result
        if: always()
        run: |
          xvfb-run pytest -m regression --alluredir=./allure-results --numprocesses 2

      #Получает Allure истории
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      #Скачиваем Allure
      - name: Allure Report action from marketplace
        uses: mgrybyk-org/allure-report-branch-js-action@v1
        if: always()
        with:
          report_dir: allure-results
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      #Публикуем всё на гитХаб паджест
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Обновили до стабильной v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages # Явно указываем правильное имя ветки через дефис
          publish_dir: allure-history # Новый JS-экшен генерирует отчет именно в эту папку



